name: geodev-logicout
dependencies:
  - python: 3.7.*
  - geopandas==0.6.1
  - json5==0.8.4
  - matplotlib==3.1.0
  - numpy==1.16.4
  - pandas==0.24.2
  - python-dotenv
  - requests==2.22.0
  - Shapely==1.6.4
  - python-tsp==0.3.1
